#!/usr/bin/env node
/**
 * build-cards.mjs — write the reference cards that come out of the fact base.
 *
 *   npm run cards            # write them
 *   npm run cards:verify     # fail if any is out of date (CI)
 *
 * Six of the cards in `docs/public/cards/` are nothing but repo data in a
 * letter-page layout: the BASIC and Monitor references, the Kernal jump table,
 * the memory map and the character set come from `data/*.json`, and the
 * keyboard layout from the KLE file in `assets/keyboard/`. Hand-maintaining
 * those is how the originals ended up documenting a v1.0 machine on a v1.5 ROM
 * — so they are generated here, from the same files the chapters render, and
 * CI fails if the checked-in copy has drifted.
 *
 * The other eight — the ACE, COB, DEV, VCS and KIM sheets, the connector
 * pinouts, the keyboard matrix and the keypad map — are hand-written, because
 * their content comes from boards and firmware rather than from the ROM. Each
 * cites its source in a comment at the top of the file, and
 * `scripts/check-cards.mjs` polices every card in the directory equally,
 * generated, hand-written and archived alike.
 */

import { existsSync, readFileSync, writeFileSync } from 'node:fs'
import { dirname, join, resolve } from 'node:path'
import { fileURLToPath } from 'node:url'

import { keyboardSvg } from './lib/keyboard.mjs'

const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..')
const DATA = join(ROOT, 'data')
const CARDS = join(ROOT, 'docs/public/cards')

const facts = (name) => JSON.parse(readFileSync(join(DATA, name), 'utf-8'))

// ---------------------------------------------------------------------------
// Page furniture
// ---------------------------------------------------------------------------

/** HTML-escape, then let a few typographic niceties through as entities. */
function esc(text) {
  return String(text ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
}

/**
 * Render the Markdown-ish spans the fact base carries in its prose fields. The
 * BIOS source writes its comments that way and the JSON keeps them verbatim,
 * so the cards have to understand the same things the chapters do: `code`, and
 * **bold**, which JOY's summary uses and which the card used to print with its
 * asterisks still attached.
 */
function rich(text) {
  return esc(text)
    .replace(/`([^`]+)`/g, '<code>$1</code>')
    .replace(/\*\*([^*]+)\*\*/g, '<strong>$1</strong>')
}

/** Two columns is the house default; a page asks for another count by name. */
const COLUMN_CLASS = { 1: ' one-col', 2: '', 3: ' three-col' }

function card({ file, title, side, subtitle, bodyClass = '', style = '', pages }) {
  const head = [
    '<!DOCTYPE html>',
    '<html lang="en">',
    '<head>',
    '<meta charset="UTF-8">',
    '<meta name="viewport" content="width=device-width, initial-scale=1.0">',
    `<title>${esc(title)}</title>`,
    '<link rel="stylesheet" href="card.css">',
    '</head>',
    `<body class="card${bodyClass ? ' ' + bodyClass : ''}"${style ? ` style="${style}"` : ''}>`,
    '',
    '<!-- Generated by scripts/build-cards.mjs from data/*.json — do not edit by hand. -->',
    '',
    '<div class="print-hint">To print: letter &middot; 100% scale &middot; margins off &middot; background graphics ON</div>'
  ]

  const body = pages.map((page, i) => {
    const label =
      pages.length <= 2 ? (i === 0 ? 'FRONT' : 'BACK') : `${i + 1} / ${pages.length}`
    return [
      '',
      `<!-- ═══════════════════════════════════════════════════ PAGE ${i + 1} -->`,
      '<div class="page">',
      '',
      '  <div class="pg-header">',
      `    <h1>${esc(page.heading ?? title)}</h1>`,
      `    <div class="side-info">${side}</div>`,
      '  </div>',
      '',
      `  <div class="pg-body${COLUMN_CLASS[page.cols ?? 2]}">`,
      indent(page.sections.join('\n'), 4),
      '  </div><!-- /pg-body -->',
      '',
      '  <div class="pg-footer">',
      `    <span>${esc(subtitle)}</span>`,
      '    <span>A.C. WRIGHT 6502</span>',
      `    <span class="pg-num">${label}</span>`,
      '  </div>',
      '',
      '</div><!-- /page -->'
    ].join('\n')
  })

  return {
    file,
    content: [...head, ...body, '', '</body>', '</html>', ''].join('\n')
  }
}

function indent(text, spaces) {
  const pad = ' '.repeat(spaces)
  return text
    .split('\n')
    .map((line) => (line.trim() ? pad + line : line))
    .join('\n')
}

function section(title, ...blocks) {
  return sectionWith('section', title, ...blocks)
}

/**
 * A section that runs on across a column break instead of being kept whole.
 *
 * The default is to keep a section together, which is right for a short table
 * with a note under it. It is wrong for a long list: a 64-row table cannot fit
 * in one column whatever the browser does, so `break-inside: avoid` first
 * pushes the whole thing to the next column — stranding whatever was left of
 * the one before it — and only then breaks it anyway. Two of those on a page
 * is how the character set ended up running off the right-hand edge.
 */
function flowSection(title, ...blocks) {
  return sectionWith('section flow', title, ...blocks)
}

function sectionWith(cls, title, ...blocks) {
  return [
    `<div class="${cls}">`,
    `  <span class="sec-title">${esc(title)}</span>`,
    indent(blocks.filter(Boolean).join('\n'), 2),
    '</div>'
  ].join('\n')
}

function table(headers, rows) {
  const head = headers.length
    ? `  <thead><tr>${headers.map((h) => `<th${h.width ? ` style="width:${h.width}"` : ''}>${esc(h.label)}</th>`).join('')}</tr></thead>`
    : ''
  const body = rows
    .map((cells) => `    <tr>${cells.map((c) => `<td class="${c.cls ?? 'td-desc'}"${c.span ? ` colspan="${c.span}"` : ''}>${c.html}</td>`).join('')}</tr>`)
    .join('\n')
  return ['<table>', head, '  <tbody>', body, '  </tbody>', '</table>'].filter(Boolean).join('\n')
}

function note(strong, text) {
  return `<div class="note-box">${strong ? `<strong>${esc(strong)}</strong> ` : ''}${text}</div>`
}

const cmd = (html) => ({ cls: 'td-cmd', html })
const syn = (html) => ({ cls: 'td-syn', html })
const addr = (html) => ({ cls: 'td-addr', html })
const label = (html) => ({ cls: 'td-label', html })
const desc = (html) => ({ cls: 'td-desc', html })

const SIDE = (line) => `A.C. Wright 6502 BIOS<br>${line}`

/**
 * Lowercase a sentence's first word so it can be joined into a list — unless
 * that word is an acronym, which stays as it was written. "The BRK statement"
 * wants to become "the BRK statement"; "ESC at the boot splash" does not want
 * to become "eSC at the boot splash", which is what the card used to print.
 */
function lowerFirst(text) {
  const first = text.split(' ', 1)[0]
  if (first === first.toUpperCase() && /[A-Z]/.test(first)) return text
  return text.charAt(0).toLowerCase() + text.slice(1)
}

// ---------------------------------------------------------------------------
// BASIC reference
// ---------------------------------------------------------------------------

/**
 * Syntax and one-line summary come from `basic-examples.json`, not from
 * `basic-keywords.json`.
 *
 * The generated keywords file carries the BIOS README's text, and Phase 4
 * found six places where that text is wrong — a `NEXT var, var` form the ROM
 * rejects, seven syntax lines pasted from the neighboring entry (ACCURACY.md
 * A21–A26). The examples file is the hand-authored, machine-run correction,
 * and it is what the chapters print. A card that disagreed with the chapter it
 * condenses would be worse than no card.
 */
function basicReference() {
  const keywords = facts('basic-keywords.json')
  const examples = facts('basic-examples.json').keywords
  const errors = facts('errors.json')
  const version = keywords.$meta.biosVersion

  const entry = (name) => {
    const k = keywords.keywords.find((w) => w.name === name)
    const e = examples[name]
    return {
      name,
      kind: k?.kind ?? 'statement',
      token: k?.token,
      syntax: e?.syntax ?? k?.forms?.[0]?.syntax ?? name,
      summary: e?.summary ?? k?.forms?.[0]?.description ?? ''
    }
  }

  const rows = (list) =>
    table(
      [{ label: 'Keyword', width: '22%' }, { label: 'Syntax', width: '38%' }, { label: 'What it does' }],
      list.map((k) => [cmd(esc(k.name)), syn(esc(k.syntax)), desc(rich(k.summary))])
    )

  /**
   * One keyword group as a section. They run on across a column break rather
   * than jumping whole to the next column: on a two-page card the stranded
   * column tails are what the third page was mostly made of.
   */
  const kwSection = (title, list) => flowSection(title, rows(list))

  // Grouped by the job, not by the token table's order. Whatever the groups
  // miss falls into "Everything else", so a keyword added to the ROM appears
  // on the card the moment the fact base is re-extracted, rather than silently
  // vanishing off it.
  const GROUPS = {
    control: ['LET', 'PRINT', 'INPUT', 'GOTO', 'GOSUB', 'RETURN', 'ON', 'IF', 'THEN', 'ELSE',
      'FOR', 'TO', 'STEP', 'NEXT', 'DEF', 'FN', 'END', 'STOP', 'CONT', 'REM'],
    program: ['RUN', 'LIST', 'NEW', 'CLR', 'DIM', 'DATA', 'READ', 'RESTORE'],
    screen: ['CLS', 'LOCATE', 'COLOR', 'SOUND', 'VOL', 'INKEY', 'JOY', 'WAIT', 'PAUSE'],
    files: ['LOAD', 'SAVE', 'DIR', 'DEL', 'DISK', 'FORMAT', 'BLOAD', 'BSAVE'],
    clock: ['TIME', 'DATE', 'SETTIME', 'SETDATE', 'NVRAM'],
    machine: ['PEEK', 'POKE', 'SYS', 'BANK', 'MEM', 'FRE', 'BRK']
  }

  const known = new Set(Object.values(GROUPS).flat())
  for (const name of known) {
    if (!keywords.keywords.some((k) => k.name === name)) {
      throw new Error(`basic-reference: grouped "${name}" is not in the token table any more`)
    }
  }

  const group = (key) => GROUPS[key].map(entry)
  const rest = keywords.keywords.filter((k) => !known.has(k.name)).map((k) => entry(k.name))
  const control = group('control')
  const program = group('program')
  const screen = group('screen')
  const files = group('files')
  const clock = group('clock')
  const machine = group('machine')

  const precedence = table(
    [{ label: 'Rank', width: '14%' }, { label: 'Level', width: '38%' }, { label: 'Operators' }],
    keywords.operatorPrecedence.map((p) => [
      cmd(String(p.rank)),
      desc(esc(p.level)),
      syn(p.operators.map((o) => `<code>${esc(o)}</code>`).join(' '))
    ])
  )

  const errorRows = table(
    [{ label: 'The machine prints', width: '46%' }, { label: 'Because' }],
    errors.basic.errors.map((e) => {
      const cause = ERROR_CAUSE[e.text]
      if (!cause) throw new Error(`basic-reference: no cause written for "${e.printed}"`)
      return [cmd(esc(e.printed)), desc(esc(cause))]
    })
  )

  return card({
    file: 'basic-reference.html',
    title: '6502 BASIC V2.0 — Reference',
    side: SIDE(`BASIC V2.0 &middot; BIOS v${version}`),
    subtitle: `6502 BASIC — QUICK REFERENCE`,
    // Two pages, not three. The keyword tables carry the card, so this is the
    // one sheet that sets its rows tighter than the house default — 1.15 line
    // and half a point of cell padding, which is about 13% off every row and
    // the difference between 1.98 pages of content and 1.82. Nothing is cut.
    style: '--w-cmd: 22%; --w-syn: 38%; --lh-table: 1.15; --pad-td: 0.5px 3.5px',
    pages: [
      {
        heading: 'BASIC Reference',
        sections: [
          section('The shape of a program',
            note('Two modes.',
              'Type a line with a number in front and it is <em>stored</em>; type one without and it ' +
              'runs there and then. <code>RUN</code> runs what is stored, <code>LIST</code> shows it, ' +
              '<code>NEW</code> throws it away. The prompt is <code>OK</code>.'),
            note('Names.',
              'Any length, letters and digits — but only the <strong>first two characters</strong> ' +
              'count, so <code>COUNT</code> and <code>COURSE</code> are the same variable. A name ' +
              'containing a keyword will not parse: <code>SCORE</code> has <code>OR</code> in it.'),
            note('Numbers.',
              'Five-byte floats, about ±1.7&nbsp;×&nbsp;10<sup>38</sup>, nine significant digits. ' +
              'A positive number prints with a leading space where the minus sign would go.')),
          kwSection('Control and flow', control),
          kwSection('The program itself', program),
          kwSection('Screen, sound and sticks', screen),
          kwSection('Files on the card', files),
          kwSection('Clock and lasting memory', clock)
        ]
      },
      {
        heading: 'BASIC Reference',
        sections: [
          kwSection('Reaching the machine', machine),
          kwSection('Functions', rest),
          section('Operator precedence', precedence,
            note('Truth is −1.',
              'A comparison gives <code>-1</code> for true and <code>0</code> for false, and ' +
              '<code>AND</code>, <code>OR</code> and <code>NOT</code> work <em>bitwise</em> on the ' +
              'integer part — which is exactly why the joystick test is ' +
              '<code>IF (JOY(1) AND 16) = 0</code>.')),
          section('Three things that catch everyone',
            note('The loop body always runs once.',
              '<code>FOR</code> tests its limit at the <code>NEXT</code>, so ' +
              '<code>FOR N = 1 TO 0</code> still runs the body one time.'),
            note('One NEXT per loop.',
              '<code>NEXT J, I</code> is not accepted, whatever else you may have read — it fails ' +
              'mid-loop with <code>?NEXT WITHOUT FOR ERROR</code>. Close each loop with its own ' +
              '<code>NEXT</code>.'),
            note('The joystick reads backwards.',
              'A direction being <em>held</em> reads <code>0</code>, not 1. An untouched stick is ' +
              '<code>255</code>.')),
          flowSection('Every error message', errorRows),
          section('Getting out of trouble',
            table([{ label: 'Key', width: '30%' }, { label: 'Does' }], [
              [cmd('Esc'), desc('Stops a running program. <strong>This is the one to remember.</strong>')],
              [cmd('Ctrl + C'), desc('The same thing, for people used to typing it')],
              [cmd('CONT'), desc('Carries on from where <code>STOP</code> or Esc left off')],
              [cmd('Reset button'), desc('Warm start — your program and variables survive')]
            ]))
        ]
      }
    ]
  })
}

/**
 * One line of cause per ROM error string.
 *
 * The ROM stores the words and nothing else, so "why did I get this" is
 * writing rather than extraction — the same sentences the errors chapter uses.
 */
const ERROR_CAUSE = {
  SYNTAX: 'BASIC could not parse the line — a typo, a missing bracket, or a keyword buried in a name',
  OVERFLOW: 'A result too big for a five-byte float',
  'OUT OF MEMORY': 'Program, variables and the GOSUB / FOR stack together filled the space',
  "UNDEF'D STATEMENT": 'GOTO or GOSUB naming a line number that is not in the program',
  'BAD SUBSCRIPT': 'An array index outside 0 to the size given to DIM',
  "REDIM'D ARRAY": 'DIM used twice on the same array',
  'DIVISION BY ZERO': 'A divide with zero on the bottom',
  'ILLEGAL DIRECT': 'A statement that only works inside a program, typed at the prompt',
  'TYPE MISMATCH': 'A string where a number belongs, or the other way around',
  'STRING TOO LONG': 'A string over 255 characters',
  'FORMULA TOO COMPLEX': 'An expression nested deeper than the evaluator can hold',
  'ILLEGAL QUANTITY': 'A number outside what the statement accepts — voice 0, volume 16, color 16',
  'RETURN WITHOUT GOSUB': 'A RETURN reached without a GOSUB to come back from',
  'NEXT WITHOUT FOR': 'A NEXT with no FOR open — or a comma list after it, which is not accepted',
  'OUT OF DATA': 'READ ran past the last DATA item. RESTORE goes back to the start',
  'NO DEVICE': 'The statement needs a card this machine has not got',
  "CAN'T CONTINUE": 'CONT after an error, NEW, CLR or RUN — there is nothing to resume'
}

// ---------------------------------------------------------------------------
// Monitor reference
// ---------------------------------------------------------------------------

function monitorReference() {
  const monitor = facts('monitor-commands.json')
  const errors = facts('errors.json')
  const version = monitor.$meta.biosVersion

  // Two commands document themselves in a shape that reads as a paragraph
  // rather than as a syntax line. On a card, the line has to fit the column.
  const SYNTAX_OVERRIDE = {
    N: 'N $XXXX | +DDDDD | %BBBB',
    ';': '; PC xxxx A xx X xx Y xx SP xx P xx',
    '#': '# [NN]'
  }

  const rows = monitor.commands.map((c) => [
    cmd(esc(c.command)),
    syn(esc(SYNTAX_OVERRIDE[c.command] ?? c.syntax ?? c.readmeSyntax ?? c.command)),
    desc(rich(c.summary) + (c.notes?.length ? ` <em>${rich(c.notes.join(' '))}</em>` : ''))
  ])

  const messages = table(
    [{ label: 'Message', width: '40%' }, { label: 'When' }],
    errors.monitorMessages.map((m) => {
      const text = m.text.replace(/\\r\\n/g, '').trim()
      const when = MONITOR_MESSAGE_CAUSE[m.symbol]
      if (when === undefined) throw new Error(`monitor-reference: no cause written for ${m.symbol}`)
      return [cmd(esc(text)), desc(rich(when))]
    })
  )

  return card({
    file: 'monitor-reference.html',
    title: '6502 Monitor — Reference',
    side: SIDE(`Monitor v1.1 &middot; BIOS v${version}`),
    subtitle: '6502 MONITOR — QUICK REFERENCE',
    style: '--w-cmd: 12%; --w-syn: 34%',
    // One page, two columns. The whole Monitor is seventeen commands and four
    // short explanations — spread over two sheets it was two-fifths white
    // space, and a card you have to turn over to find the register line is a
    // card you stop turning over.
    pages: [
      {
        heading: 'Monitor Reference',
        sections: [
          section('Getting in and out',
            note('Three ways in.',
              monitor.entryRoutes.map((r) => esc(lowerFirst(r))).join('; ') +
              `. The prompt is a single <code>${esc(monitor.prompt)}</code>.`),
            note('One way out.',
              'Type <code>X</code>. BASIC comes back warm — your program and variables are still there.'),
            table([{ label: 'Entry', width: '30%' }, { label: 'Address', width: '18%' }, { label: 'Used by' }],
              monitor.entryPoints.map((e) => [
                cmd(esc(e.name)), addr(esc(e.address)), desc(esc(e.description))
              ]))),
          section('Every command',
            table([{ label: 'Cmd', width: '12%' }, { label: 'Syntax', width: '34%' }, { label: 'What it does' }], rows)),
          section('Reading the register line',
            `<div class="reg-display">PC=E9D3 A=00 X=FF Y=68 SP=FA ${esc(errors.monitorRegisterHeader.text)}</div>`,
            note(null,
              esc(errors.monitorRegisterHeader.description) +
              ' A flag letter shown means the bit is set; a dash means it is clear. ' +
              '<code>;</code> writes the same fields back.')),
          section('Numbers',
            note(null,
              'Addresses are typed as bare hex — <code>M 0800</code>, not <code>M $0800</code>. ' +
              'The <code>N</code> command is the exception and wants a prefix: <code>$</code> hex, ' +
              '<code>+</code> decimal, <code>%</code> binary. It answers in all three.'),
            '<div class="reg-display">. N $FF00\n$FF00  +65280  %1111111100000000</div>'),
          section('Go versus Jump',
            note('Use J.',
              `<code>J ${monitor.wozmon.address.slice(1)}</code> calls the code at an address and comes ` +
              'back to the monitor when it hits <code>RTS</code>. <code>G</code> hands the machine over ' +
              'for good — and it turns interrupts off on the way, so anything that waits for a keypress ' +
              'will sit there for ever.'),
            note('The Wozmon easter egg.',
              `<code>${esc(monitor.wozmon.fromMonitor)}</code> from here, or ` +
              `<code>${esc(monitor.wozmon.fromBasic)}</code> from BASIC, lands you in a copy of the ` +
              'original Apple I monitor. Its prompt is a backslash. <code>FF00.FF07</code> reads eight ' +
              'bytes; <code>0800: A9 41</code> writes two.')),
          section('The messages it prints', messages)
        ]
      }
    ]
  })
}

/** When each Monitor string appears. The ROM holds the words, not the reason. */
const MONITOR_MESSAGE_CAUSE = {
  MonStrBanner: 'On the way in, whichever route you came by',
  MonStrBrk: 'A `BRK` was hit — the address that follows is where',
  MonStrNotFound: '`L "NAME"` and there is no such file on the current disk',
  MonStrDirFull: '`S "NAME"` on a disk that already holds sixteen files',
  MonStrLoadPfx: 'A load finished — the byte count and address follow',
  MonStrSavePfx: 'A save finished',
  MonStrBytesAt: 'Tail of the load and save reports',
  MonStrBytes: 'Tail of a report that has no address to give',
  MonStrIOErr: 'The CompactFlash card did not answer'
}

// ---------------------------------------------------------------------------
// Kernal jump table
// ---------------------------------------------------------------------------

function kernalJumpTable() {
  const kernal = facts('kernal.json')
  const version = kernal.$meta.biosVersion
  const bySlot = Object.fromEntries(kernal.slots.map((s) => [s.name, s]))

  // Grouped the way a programmer arrives at them, which is not the order the
  // table is laid out in — the same grouping docs/assembly/kernal.md uses.
  const GROUPS = [
    ['Console', ['Chrout', 'Chrin', 'PrintStr', 'PrintCRLF', 'PrintDecU16', 'WriteBuffer', 'ReadBuffer', 'BufferSize', 'SetIOMode', 'GetIOMode']],
    ['The screen', ['InitVideo', 'VideoClear', 'VideoPutChar', 'VideoChroutRaw', 'VideoSetCursor', 'VideoGetCursor', 'VideoScroll', 'VideoSetColor']],
    ['Sound', ['InitSID', 'Beep', 'SidPlayNote', 'SidSilence', 'SidSetVolume']],
    ['Keyboard and sticks', ['InitKB', 'ReadJoystick1', 'ReadJoystick2', 'KBDisable', 'KBEnable']],
    ['Files', ['FsLoadFileAddr', 'FsSaveFileAddr', 'FsLoadFile', 'FsSaveFile', 'FsDeleteFile', 'FsFormatDisk', 'FsSetDisk', 'FsGetDisk', 'FsPrintDisk']],
    ['The card itself', ['StReadSector', 'StWriteSector', 'StWaitReady']],
    ['Serial', ['InitSC', 'SerialChrout', 'XModemLoad', 'XModemSave']],
    ['Clock and lasting memory', ['RtcReadTime', 'RtcReadDate', 'RtcWriteTime', 'RtcWriteDate', 'RtcReadNVRAM', 'RtcWriteNVRAM']],
    ['The machine', ['SysDelay', 'KernalInit', 'KernalVersion']]
  ]

  const listed = new Set(GROUPS.flatMap(([, names]) => names))
  const missing = kernal.slots.filter((s) => !listed.has(s.name))
  if (missing.length) {
    throw new Error(`kernal-jump-table: ${missing.length} slot(s) ungrouped: ${missing.map((s) => s.name).join(', ')}`)
  }

  const group = (title, names) =>
    section(title,
      table([{ label: 'Addr', width: '13%' }, { label: 'Name', width: '28%' }, { label: 'In / out' }],
        names.map((n) => {
          const s = bySlot[n]
          if (!s) throw new Error(`kernal-jump-table: no slot named ${n}`)
          const io = [
            s.input?.length ? `<strong>in</strong> ${esc(s.input.join('; '))}` : '',
            s.output?.length ? `<strong>out</strong> ${esc(s.output.join('; '))}` : ''
          ].filter(Boolean).join(' &middot; ')
          return [addr(esc(s.address)), label(esc(s.name)), desc(`${rich(s.summary)}${io ? `<br>${io}` : ''}`)]
        })))

  const half = (from, to) => GROUPS.slice(from, to).map(([t, n]) => group(t, n))

  return card({
    file: 'kernal-jump-table.html',
    title: '6502 Kernal — Jump Table',
    side: SIDE(`Kernal &middot; BIOS v${version}`),
    subtitle: '6502 KERNAL — JUMP TABLE',
    style: '--w-addr: 13%; --w-label: 28%',
    pages: [
      {
        heading: 'Kernal Jump Table',
        sections: [
          section('The contract',
            note('Call the slot, never the implementation.',
              `${kernal.publishedSlots} entry points, three bytes each, starting at ` +
              `<code>${esc(kernal.base)}</code> and in an order that does not change. ` +
              `<code>jsr ${esc(kernal.base)}</code> prints a character on this ROM and on the next one. ` +
              `<code>6502.inc</code> gives every slot its name, so you will write <code>jsr Chrout</code>.`),
            note('Arguments go in registers.',
              'A, X and Y in, A, X, Y or the carry flag out. Nothing is passed on the stack.'),
            note('The tail of the table.',
              `${kernal.reserved.count} slots from <code>${esc(kernal.reserved.start)}</code> to ` +
              `<code>${esc(kernal.reserved.end)}</code> are reserved. Each is a real jump to a bare ` +
              '<code>RTS</code>, so calling one is harmless now and may do something later. Do not put ' +
              'your own code there.')),
          ...half(0, 4)
        ]
      },
      { heading: 'Kernal Jump Table', sections: half(4, 9) }
    ]
  })
}

// ---------------------------------------------------------------------------
// F18A registers
// ---------------------------------------------------------------------------

/**
 * The one card in the set whose data does not come from this ecosystem at all.
 *
 * `f18a.json` is transcribed from Matthew Hagerty's F18A register sheet and
 * Troy Schrapel's Pico9918 reference, because the enhanced mode of the ACE's
 * video card is defined by those and by nothing in any repo here. It is also
 * the one card describing something the emulator cannot run, which is exactly
 * why it wants to be on paper: the reader checking it is sitting in front of
 * real hardware with no way to ask the machine.
 *
 * Bit order is flipped on the way in — Hagerty numbers the most significant
 * bit as 0 — and that conversion lives in the JSON, not here, so the card and
 * the chapter cannot disagree about which end a bit is.
 */
function f18aRegisters() {
  const f18a = facts('f18a.json')

  const bitRows = (bits) =>
    bits.map((b) => [
      addr(esc(b.bits)),
      label(esc(b.name)),
      desc(rich(b.description) + (b.pico ? ' <em>(Pico9918)</em>' : b.enhanced ? ' <em>(needs unlocking)</em>' : ''))
    ])

  /** One register: a heading row, then a row per bit field, or just the summary. */
  const regBlock = (r) => {
    const head = `<div class="reg-head"><strong>VR${r.reg}</strong> <span class="reg-hex">${esc(r.hex)} / ctrl ${esc(r.ctrl)}</span> &mdash; ${esc(r.name)}${r.pico ? ' <em>(Pico9918)</em>' : ''}</div>`
    const body = r.bits
      ? table([], bitRows(r.bits))
      : `<div class="reg-sum">${rich(r.summary)}</div>`
    return head + '\n' + body
  }

  const standard = f18a.registers.filter((r) => r.standard)
  const enhanced = f18a.registers.filter((r) => !r.standard)

  const statusRows = f18a.statusRegisters.map((s) => [
    addr(`SR${s.sr}`),
    desc(rich(s.summary) + (s.pico ? ' <em>(Pico9918)</em>' : s.f18aOnly ? ' <em>(F18A only)</em>' : ''))
  ])

  const modeRows = f18a.modes.map((m) => [
    label(esc(m.name)),
    desc(`M1 ${m.m1} &middot; M2 ${m.m2} &middot; M3 ${m.m3} &middot; M4 ${m.m4}`)
  ])

  const ecmRows = f18a.colorModes.map((m) => [
    label(m.ecm === 0 ? 'Original' : `ECM${m.ecm}`),
    desc(`${m.colors} colors per tile, ${m.spriteColors} per sprite &middot; ${m.planes} plane${m.planes > 1 ? 's' : ''} &middot; ${m.patternTable} pattern table &middot; ${m.palettes} palettes`)
  ])

  // The caveat rides on the card as well as in the chapter. Whoever is holding
  // this sheet is standing at the hardware without the guide open, and D4 of a
  // sprite's attribute byte is the one bit the two references describe
  // differently — exactly the thing you want to know before you rely on it.
  const attrBlock = (a) =>
    section(a.title,
      table([], bitRows(a.bits)),
      a.conflict ? note('The sources disagree.', esc(a.conflict)) : '')

  return card({
    file: 'f18a-registers.html',
    title: 'F18A Mode — Register Reference',
    side: SIDE('F18A mode &middot; Pico9918'),
    subtitle: 'F18A MODE — REGISTERS',
    style: '--w-addr: 22%; --w-label: 22%',
    pages: [
      {
        heading: 'F18A Mode — Registers',
        sections: [
          section('Unlocking',
            note('Write $1C to VR57. Twice, consecutively.',
              `${esc(f18a.unlock.why)} Any other register write between the two cancels it. ` +
              `<strong>${esc(f18a.unlock.hazard)}</strong>`),
            note('Writing a register.',
              'Value to <code>$9C01</code>, then the register number with bit 7 set. ' +
              'Registers 0&ndash;7 always; 8&ndash;63 only once unlocked.'),
            note('Which card is this?',
              `Status register 1 reads <code>$E0</code> on a real F18A and <code>$E8</code> on a ` +
              `Pico9918. Select it with VR15, read <code>$9C01</code>, then <strong>put VR15 back to 0</strong>.`),
            note('Bit order.',
              'D7 is the most significant bit here. Hagerty&rsquo;s own documents number the ' +
              'most significant bit as 0, so his tables read mirrored against these.')),
          section('Display modes', table([], modeRows)),
          flowSection('Registers 0–7 (always available)',
            standard.map(regBlock).join('\n')),
          flowSection('Registers 10–34 (unlocked only)',
            enhanced.filter((r) => r.reg <= 34).map(regBlock).join('\n'))
        ]
      },
      {
        heading: 'F18A Mode — Registers',
        sections: [
          flowSection('Registers 35–63 (unlocked only)',
            enhanced.filter((r) => r.reg >= 35).map(regBlock).join('\n')),
          section('Status registers', table([], statusRows)),
          section('Enhanced color modes', table([], ecmRows)),
          attrBlock(f18a.attributes.spriteUnlocked),
          attrBlock(f18a.attributes.tile),
          section('Before you trust this',
            note('It cannot be checked here.',
              'F18A mode exists on hardware only. Everything on this card is transcribed from ' +
              'Matthew Hagerty&rsquo;s F18A register sheet and the Pico9918 reference; where those ' +
              'two disagree, the guide says so and this card follows the guide.'))
        ]
      }
    ]
  })
}

// ---------------------------------------------------------------------------
// Memory map
// ---------------------------------------------------------------------------

function memoryMap() {
  const map = facts('memory-map.json')
  const hardware = facts('hardware.json')
  const version = map.$meta.biosVersion

  const size = (n) => (n >= 1024 ? `${Math.round((n / 1024) * 10) / 10} KB` : `${n} B`)

  const ram = table(
    [{ label: 'Range', width: '26%' }, { label: 'Size', width: '14%' }, { label: 'What lives there' }],
    map.ram.map((r) => [
      addr(`${esc(r.start)}&ndash;${esc(r.end)}`),
      desc(size(r.size)),
      desc(rich(r.purpose ?? r.name))
    ])
  )

  // BIOS.cfg declares the I/O window as a ROM region so the image pads out to
  // 32 KB, but nothing is linked into it — so it is not a ROM segment a reader
  // could go and look at, and listing it here alongside KERNAL and BASIC would
  // suggest it is. The I/O table below is its real home.
  const rom = table(
    [{ label: 'Range', width: '26%' }, { label: 'Size', width: '14%' }, { label: 'Segment' }],
    map.rom.filter((r) => r.start !== map.io.start).map((r) => [
      addr(`${esc(r.start)}&ndash;${esc(r.end)}`),
      desc(size(r.size)),
      desc(esc(r.name))
    ])
  )

  const slots = table(
    [{ label: 'Slot', width: '9%' }, { label: 'Range', width: '24%' }, { label: 'Bit', width: '10%' }, { label: 'Card' }],
    hardware.slots.map((s) => [
      cmd(String(s.slot)),
      addr(`${esc(s.start)}&ndash;${esc(s.end)}`),
      addr(esc(s.maskHex)),
      desc(`${esc(s.card)} &mdash; ${esc(s.chip)}`)
    ])
  )

  const registers = (slot) =>
    section(`${slot.card} — ${slot.start}`,
      table([{ label: 'Address', width: '24%' }, { label: 'Register' }],
        slot.registers.map((r) => [
          addr(esc(r.address)),
          desc(`<code>${esc(r.symbol)}</code>${r.description ? ' &mdash; ' + esc(r.description) : ''}`)
        ])))

  const bySymbol = Object.fromEntries(hardware.slots.map((s) => [s.symbol, s]))

  return card({
    file: 'memory-map.html',
    title: '6502 Memory Map',
    side: SIDE(`Memory map &middot; BIOS v${version}`),
    subtitle: '6502 MEMORY MAP',
    style: '--w-addr: 26%',
    pages: [
      {
        heading: 'Memory Map',
        sections: [
          section('The whole 64 KB',
            table([{ label: 'Range', width: '26%' }, { label: 'What it is' }], [
              [addr('$0000&ndash;$00FF'), desc('Zero page &mdash; Kernal, BASIC and Monitor workspace')],
              [addr('$0100&ndash;$01FF'), desc('The 6502 stack')],
              [addr('$0200&ndash;$07FF'), desc('Kernal and BASIC buffers &mdash; <strong>not</strong> yours')],
              [addr(`${esc(map.constants.programStart)}&ndash;$7FFF`), desc('Your program, your variables, your strings')],
              [addr(`${esc(map.io.start)}&ndash;${esc(map.io.end)}`), desc('The I/O window &mdash; eight cards, 1 KB each')],
              [addr('$A000&ndash;$B7FF'), desc('Kernal')],
              [addr('$B800&ndash;$BFFF'), desc('Character set')],
              [addr('$C000&ndash;$EDFF'), desc('BASIC')],
              [addr('$EE00&ndash;$FEFF'), desc('Monitor')],
              [addr('$FF00&ndash;$FFF9'), desc('Wozmon')],
              [addr('$FFFA&ndash;$FFFF'), desc('NMI, RESET and IRQ vectors')]
            ]),
            note('Where your bytes go.',
              `A BASIC program starts at <code>${esc(map.constants.programStart)}</code> and grows up; ` +
              `the string heap starts at <code>${esc(map.constants.stringHeapTop)}</code> and grows down. ` +
              'When they meet you get <code>?OUT OF MEMORY ERROR</code>.'),
            note('The 198 bytes that are yours.',
              'Zero page from <code>$003A</code> up is unclaimed by the Kernal &mdash; but only for a ' +
              'program that has taken the machine over. Underneath a running BASIC it is in use, and ' +
              'a <code>POKE</code> there will not stick.')),
          section('RAM, in detail', ram),
          section('ROM segments', rom,
            note('One EEPROM, three version numbers.',
              'BIOS v1.5, BASIC V2.0 and Monitor v1.1 all ship in the same 32 KB chip.')),
          section('The I/O window', slots,
            note('What the machine found.',
              `<code>${esc(hardware.hwPresent.address)}</code> holds one bit per slot, written by the ` +
              `probe at reset. <code>MEM</code> prints it as <code>HW=$xx</code>; ` +
              `<code>${esc(hardware.hwPresent.readFromBasic)}</code> reads it from BASIC.`))
        ]
      },
      // Every I/O register on one back page. Split across two sheets these
      // filled less than half a page each, and the reader who is chasing a
      // register wants them all in one place rather than in slot order across
      // a page turn.
      {
        heading: 'Memory Map',
        sections: [
          registers(bySymbol.HW_SID),
          registers(bySymbol.HW_RTC),
          registers(bySymbol.HW_CF),
          registers(bySymbol.HW_GPIO),
          registers(bySymbol.HW_SC),
          registers(bySymbol.HW_VID),
          section('Banked RAM',
            table([{ label: 'Address', width: '24%' }, { label: 'Register' }],
              [...bySymbol.HW_RAM_L.registers, ...bySymbol.HW_RAM_H.registers].map((r) => [
                addr(esc(r.address)),
                desc(`<code>${esc(r.symbol)}</code>${r.description ? ' &mdash; ' + esc(r.description) : ''}`)
              ])),
            note('256 banks of 1 KB.',
              'Write a bank number to the latch, then read and write the window below it. From BASIC ' +
              'that is <code>BANK n</code>.'))
        ]
      }
    ]
  })
}

// ---------------------------------------------------------------------------
// Character map
// ---------------------------------------------------------------------------

/*
 * A note on the section titles below: `section()` escapes what it is given, so
 * a title has to carry the dash as a character rather than as `&ndash;`. It
 * used to be written as the entity, and the card printed a heading reading
 * "$00 &NDASH; $3F".
 */

/**
 * Draw one glyph as an inline SVG from its eight ROM bytes.
 *
 * Every pixel is a 1×1 rect in an 8×8 viewBox, so the card prints at whatever
 * resolution the printer has rather than at whatever resolution a PNG was
 * exported at — and the picture is the ROM's own bits, not a screenshot of a
 * font that resembles them.
 */
function glyphSvg(rows) {
  const pixels = []
  rows.forEach((byte, y) => {
    for (let x = 0; x < 8; x++) {
      if (byte & (0x80 >> x)) pixels.push(`<rect x="${x}" y="${y}" width="1" height="1"/>`)
    }
  })
  return `<svg class="glyph" viewBox="0 0 8 8" role="img">${pixels.join('')}</svg>`
}

function characterMap() {
  const charset = facts('charset.json')
  const version = charset.$meta.biosVersion

  // Sixteen rows of sixteen, addressed the way a hex dump is: row = high
  // nibble, column = low nibble.
  const grid = (from, to) => {
    const header =
      '  <thead><tr><th class="th-hex"></th>' +
      Array.from({ length: 16 }, (_, i) => `<th class="th-hex">${i.toString(16).toUpperCase()}</th>`).join('') +
      '</tr></thead>'
    const body = []
    for (let hi = from; hi < to; hi++) {
      const cells = []
      for (let lo = 0; lo < 16; lo++) {
        const ch = charset.chars[hi * 16 + lo]
        cells.push(`<td class="td-glyph" title="${esc(ch.hex)} ${esc(ch.name)}">${glyphSvg(ch.rows)}</td>`)
      }
      body.push(`    <tr><td class="td-hex">${hi.toString(16).toUpperCase()}<em>x</em></td>${cells.join('')}</tr>`)
    }
    return ['<table class="charset-grid">', header, '  <tbody>', body.join('\n'), '  </tbody>', '</table>'].join('\n')
  }

  const names = (from, to) =>
    table([{ label: 'Code', width: '11%' }, { label: '', width: '7%' }, { label: 'Name' }],
      charset.chars.slice(from, to).map((ch) => [
        addr(esc(ch.hex)),
        { cls: 'td-glyph-inline', html: glyphSvg(ch.rows) },
        desc(esc(ch.name))
      ]))

  return card({
    file: 'character-map.html',
    title: '6502 Character Set',
    side: SIDE(`CP437 at ${charset.address} &middot; BIOS v${version}`),
    subtitle: '6502 CHARACTER SET',
    pages: [
      {
        heading: 'Character Set',
        cols: 1,
        sections: [
          section('All 256 characters',
            note(null,
              `The machine's character set is IBM Code Page 437, ${charset.cell}, living in ROM at ` +
              `<code>${esc(charset.address)}</code>. <code>InitVideo</code> copies it into the video ` +
              'card at power-on. Row is the high hex digit, column the low one &mdash; ' +
              `so <code>A</code> is row <code>4</code>, column <code>1</code>: <code>$41</code>.`),
            grid(0, 16)),
          section('What you can PRINT',
            note(null,
              `<code>PRINT</code> reaches <code>${esc(charset.printable.viaChrout)}</code> and four ` +
              'control codes &mdash; carriage return, line feed, backspace and bell. ' +
              '<strong>Everything else it throws away</strong>, including every box-drawing and ' +
              `shading glyph above <code>$7E</code>. Those need <code>${esc(charset.printable.rawRoutine)}</code>, ` +
              'which is an assembly-level call.'))
        ]
      },
      // Three columns, not two. A name row is a hex code, a glyph and two or
      // three words, so at half-page width most of the line was blank — and
      // 128 rows to a page overran the two columns by a fifth, which the page
      // box then clipped off the right edge. Narrower columns fit the content
      // they hold and give the rows somewhere to go.
      {
        heading: 'Character Set',
        cols: 3,
        sections: [
          flowSection('$00 – $3F', names(0x00, 0x40)),
          flowSection('$40 – $7F', names(0x40, 0x80))
        ]
      },
      {
        heading: 'Character Set',
        cols: 3,
        sections: [
          flowSection('$80 – $BF', names(0x80, 0xc0)),
          flowSection('$C0 – $FF', names(0xc0, 0x100))
        ]
      }
    ]
  })
}

// ---------------------------------------------------------------------------
// Keyboard layout
// ---------------------------------------------------------------------------

function keyboardLayout() {
  const { svg, count } = keyboardSvg(join(ROOT, 'assets/keyboard/keyboard-layout.json'), { escape: esc })

  return card({
    file: 'keyboard-layout.html',
    title: '6502 Keyboard Layout',
    side: `A.C. Wright 6502<br>ACE &middot; ${count} keys`,
    subtitle: '6502 KEYBOARD LAYOUT',
    pages: [
      {
        heading: 'Keyboard Layout',
        cols: 1,
        sections: [
          section("The board's own keys",
            `<figure>\n${svg}\n<figcaption>` +
            `${count} Cherry MX switches, soldered to the board. There is nothing to plug in and ` +
            'nothing to set up &mdash; the keyboard <em>is</em> the computer. The small white reset ' +
            'button sits just above <kbd>Esc</kbd>, in the top-right corner.' +
            '</figcaption>\n</figure>'),
          section('Keys that do something out of the ordinary',
            table([{ label: 'Key', width: '22%' }, { label: 'What it does' }], [
              [cmd('Esc'), desc('<strong>Stops a running program.</strong> BASIC checks between statements, so it works even inside a tight loop. At the <code>OK</code> prompt it does nothing')],
              [cmd('Esc <em>at boot</em>'), desc('Pressed during the five-second splash, takes you into the Monitor instead of BASIC')],
              [cmd('Ctrl + C'), desc('The same break, for people who type it out of habit')],
              [cmd('Ctrl + A&hellip;Z'), desc('Sends codes 1 to 26. <code>Ctrl</code>+<code>[</code> sends the same code as <kbd>Esc</kbd>')],
              [cmd('Backspace'), desc('Rubs out the last character you typed')],
              [cmd('Arrow keys'), desc('Send codes <code>$1C</code> to <code>$1F</code>. Nothing in BASIC listens for them &mdash; they are there for programs you write')],
              [cmd('Reset'), desc('<strong>Warm start.</strong> The machine comes back to <code>OK</code> with your program and variables intact. The cold start is the power switch')]
            ])),
          section('Keys that do nothing',
            note('Caps Lock, Menu, Alt and Fn are dead.',
              'The controller reads them and drops them &mdash; they send no character and hold no state.'),
            note('Caps Lock has nothing to lock.',
              'Letters come out as capitals whatever you do; Shift changes the symbols and the number ' +
              'row only. Lower case exists over the serial line and nowhere else, which is worth ' +
              'knowing before you go hunting for a setting that turns it on.')),
          section('Two other ways to type',
            note('PS/2.',
              'Plug a keyboard into the mini-DIN socket and it works <em>alongside</em> the board\'s ' +
              'keys, not instead of them. Both land in the same buffer.'),
            note('Serial.',
              'A terminal at 19200 8-N-1 gives you a third keyboard &mdash; and the only one that can ' +
              'send lower case, or paste a listing in.'),
            note('An outboard matrix.',
              'Anyone enclosing the board leaves the switches unfitted and wires their own ' +
              '8&nbsp;&times;&nbsp;8 grid to the KEYBOARD header. Same grid, same codes &mdash; see ' +
              'the Keyboard Matrix card.'))
        ]
      }
    ]
  })
}

// ---------------------------------------------------------------------------
// Main
// ---------------------------------------------------------------------------

function main() {
  const check = process.argv.includes('--check')
  const built = [
    basicReference(),
    monitorReference(),
    kernalJumpTable(),
    memoryMap(),
    characterMap(),
    keyboardLayout(),
    f18aRegisters()
  ]

  let stale = 0
  for (const { file, content } of built) {
    const path = join(CARDS, file)
    if (check) {
      const current = existsSync(path) ? readFileSync(path, 'utf-8') : ''
      if (current !== content) {
        console.error(`FAIL cards/${file} is out of date`)
        stale++
      } else {
        console.log(`ok   cards/${file}`)
      }
      continue
    }
    writeFileSync(path, content)
    console.log(`wrote cards/${file}  (${content.split('\n').length} lines)`)
  }

  if (check && stale) {
    console.error(`\n${stale} card(s) stale — run: npm run cards`)
    process.exit(1)
  }
  if (check) console.log('\nevery generated card is current with the fact base')
}

main()
